//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.IService")]
    public interface IService
    {
        
        // CODEGEN: Parameter 'GetDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StudentService.GetDataResponse GetData(StudentService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<StudentService.GetDataResponse> GetDataAsync(StudentService.GetDataRequest request);
        
        // CODEGEN: Parameter 'GetDataUsingDataContractResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StudentService.GetDataUsingDataContractResponse GetDataUsingDataContract(StudentService.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<StudentService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(StudentService.GetDataUsingDataContractRequest request);
        
        // CODEGEN: Parameter 'AddStudentsRecordResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudentsRecord", ReplyAction="http://tempuri.org/IService/AddStudentsRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StudentService.AddStudentsRecordResponse AddStudentsRecord(StudentService.AddStudentsRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudentsRecord", ReplyAction="http://tempuri.org/IService/AddStudentsRecordResponse")]
        System.Threading.Tasks.Task<StudentService.AddStudentsRecordResponse> AddStudentsRecordAsync(StudentService.AddStudentsRecordRequest request);
        
        // CODEGEN: Parameter 'GetStudentsRecordsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudentsRecords", ReplyAction="http://tempuri.org/IService/GetStudentsRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StudentService.GetStudentsRecordsResponse GetStudentsRecords(StudentService.GetStudentsRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudentsRecords", ReplyAction="http://tempuri.org/IService/GetStudentsRecordsResponse")]
        System.Threading.Tasks.Task<StudentService.GetStudentsRecordsResponse> GetStudentsRecordsAsync(StudentService.GetStudentsRecordsRequest request);
        
        // CODEGEN: Parameter 'DeleteRecordsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteRecords", ReplyAction="http://tempuri.org/IService/DeleteRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StudentService.DeleteRecordsResponse DeleteRecords(StudentService.DeleteRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteRecords", ReplyAction="http://tempuri.org/IService/DeleteRecordsResponse")]
        System.Threading.Tasks.Task<StudentService.DeleteRecordsResponse> DeleteRecordsAsync(StudentService.DeleteRecordsRequest request);
        
        // CODEGEN: Parameter 'SearchStudentsRecordResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchStudentsRecord", ReplyAction="http://tempuri.org/IService/SearchStudentsRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StudentService.SearchStudentsRecordResponse SearchStudentsRecord(StudentService.SearchStudentsRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchStudentsRecord", ReplyAction="http://tempuri.org/IService/SearchStudentsRecordResponse")]
        System.Threading.Tasks.Task<StudentService.SearchStudentsRecordResponse> SearchStudentsRecordAsync(StudentService.SearchStudentsRecordRequest request);
        
        // CODEGEN: Parameter 'UpdateStudentsContactResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateStudentsContact", ReplyAction="http://tempuri.org/IService/UpdateStudentsContactResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StudentService.UpdateStudentsContactResponse UpdateStudentsContact(StudentService.UpdateStudentsContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateStudentsContact", ReplyAction="http://tempuri.org/IService/UpdateStudentsContactResponse")]
        System.Threading.Tasks.Task<StudentService.UpdateStudentsContactResponse> UpdateStudentsContactAsync(StudentService.UpdateStudentsContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CompositeType
    {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool BoolValue
        {
            get
            {
                return this.boolValueField;
            }
            set
            {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified
        {
            get
            {
                return this.boolValueFieldSpecified;
            }
            set
            {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string StringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Student
    {
        
        private string emailField;
        
        private string genderField;
        
        private string nameField;
        
        private string phoneField;
        
        private string stdIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string StdID
        {
            get
            {
                return this.stdIDField;
            }
            set
            {
                this.stdIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.CompositeType composite;
        
        public GetDataUsingDataContractRequest()
        {
        }
        
        public GetDataUsingDataContractRequest(StudentService.CompositeType composite)
        {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse()
        {
        }
        
        public GetDataUsingDataContractResponse(StudentService.CompositeType GetDataUsingDataContractResult)
        {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStudentsRecord", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddStudentsRecordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.Student std;
        
        public AddStudentsRecordRequest()
        {
        }
        
        public AddStudentsRecordRequest(StudentService.Student std)
        {
            this.std = std;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStudentsRecordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddStudentsRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddStudentsRecordResult;
        
        public AddStudentsRecordResponse()
        {
        }
        
        public AddStudentsRecordResponse(string AddStudentsRecordResult)
        {
            this.AddStudentsRecordResult = AddStudentsRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentsRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentsRecordsRequest
    {
        
        public GetStudentsRecordsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentsRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentsRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.ArrayOfXElement GetStudentsRecordsResult;
        
        public GetStudentsRecordsResponse()
        {
        }
        
        public GetStudentsRecordsResponse(StudentService.ArrayOfXElement GetStudentsRecordsResult)
        {
            this.GetStudentsRecordsResult = GetStudentsRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRecordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.Student std;
        
        public DeleteRecordsRequest()
        {
        }
        
        public DeleteRecordsRequest(StudentService.Student std)
        {
            this.std = std;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeleteRecordsResult;
        
        public DeleteRecordsResponse()
        {
        }
        
        public DeleteRecordsResponse(string DeleteRecordsResult)
        {
            this.DeleteRecordsResult = DeleteRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchStudentsRecord", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchStudentsRecordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.Student std;
        
        public SearchStudentsRecordRequest()
        {
        }
        
        public SearchStudentsRecordRequest(StudentService.Student std)
        {
            this.std = std;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchStudentsRecordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchStudentsRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.ArrayOfXElement SearchStudentsRecordResult;
        
        public SearchStudentsRecordResponse()
        {
        }
        
        public SearchStudentsRecordResponse(StudentService.ArrayOfXElement SearchStudentsRecordResult)
        {
            this.SearchStudentsRecordResult = SearchStudentsRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudentsContact", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentsContactRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StudentService.Student std;
        
        public UpdateStudentsContactRequest()
        {
        }
        
        public UpdateStudentsContactRequest(StudentService.Student std)
        {
            this.std = std;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudentsContactResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentsContactResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateStudentsContactResult;
        
        public UpdateStudentsContactResponse()
        {
        }
        
        public UpdateStudentsContactResponse(string UpdateStudentsContactResult)
        {
            this.UpdateStudentsContactResult = UpdateStudentsContactResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceChannel : StudentService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<StudentService.IService>, StudentService.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentService.GetDataResponse StudentService.IService.GetData(StudentService.GetDataRequest request)
        {
            return base.Channel.GetData(request);
        }
        
        public string GetData(int value)
        {
            StudentService.GetDataRequest inValue = new StudentService.GetDataRequest();
            inValue.value = value;
            StudentService.GetDataResponse retVal = ((StudentService.IService)(this)).GetData(inValue);
            return retVal.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentService.GetDataResponse> StudentService.IService.GetDataAsync(StudentService.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetDataResponse> GetDataAsync(int value)
        {
            StudentService.GetDataRequest inValue = new StudentService.GetDataRequest();
            inValue.value = value;
            return ((StudentService.IService)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentService.GetDataUsingDataContractResponse StudentService.IService.GetDataUsingDataContract(StudentService.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public StudentService.CompositeType GetDataUsingDataContract(StudentService.CompositeType composite)
        {
            StudentService.GetDataUsingDataContractRequest inValue = new StudentService.GetDataUsingDataContractRequest();
            inValue.composite = composite;
            StudentService.GetDataUsingDataContractResponse retVal = ((StudentService.IService)(this)).GetDataUsingDataContract(inValue);
            return retVal.GetDataUsingDataContractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentService.GetDataUsingDataContractResponse> StudentService.IService.GetDataUsingDataContractAsync(StudentService.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(StudentService.CompositeType composite)
        {
            StudentService.GetDataUsingDataContractRequest inValue = new StudentService.GetDataUsingDataContractRequest();
            inValue.composite = composite;
            return ((StudentService.IService)(this)).GetDataUsingDataContractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentService.AddStudentsRecordResponse StudentService.IService.AddStudentsRecord(StudentService.AddStudentsRecordRequest request)
        {
            return base.Channel.AddStudentsRecord(request);
        }
        
        public string AddStudentsRecord(StudentService.Student std)
        {
            StudentService.AddStudentsRecordRequest inValue = new StudentService.AddStudentsRecordRequest();
            inValue.std = std;
            StudentService.AddStudentsRecordResponse retVal = ((StudentService.IService)(this)).AddStudentsRecord(inValue);
            return retVal.AddStudentsRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentService.AddStudentsRecordResponse> StudentService.IService.AddStudentsRecordAsync(StudentService.AddStudentsRecordRequest request)
        {
            return base.Channel.AddStudentsRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.AddStudentsRecordResponse> AddStudentsRecordAsync(StudentService.Student std)
        {
            StudentService.AddStudentsRecordRequest inValue = new StudentService.AddStudentsRecordRequest();
            inValue.std = std;
            return ((StudentService.IService)(this)).AddStudentsRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentService.GetStudentsRecordsResponse StudentService.IService.GetStudentsRecords(StudentService.GetStudentsRecordsRequest request)
        {
            return base.Channel.GetStudentsRecords(request);
        }
        
        public StudentService.ArrayOfXElement GetStudentsRecords()
        {
            StudentService.GetStudentsRecordsRequest inValue = new StudentService.GetStudentsRecordsRequest();
            StudentService.GetStudentsRecordsResponse retVal = ((StudentService.IService)(this)).GetStudentsRecords(inValue);
            return retVal.GetStudentsRecordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentService.GetStudentsRecordsResponse> StudentService.IService.GetStudentsRecordsAsync(StudentService.GetStudentsRecordsRequest request)
        {
            return base.Channel.GetStudentsRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetStudentsRecordsResponse> GetStudentsRecordsAsync()
        {
            StudentService.GetStudentsRecordsRequest inValue = new StudentService.GetStudentsRecordsRequest();
            return ((StudentService.IService)(this)).GetStudentsRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentService.DeleteRecordsResponse StudentService.IService.DeleteRecords(StudentService.DeleteRecordsRequest request)
        {
            return base.Channel.DeleteRecords(request);
        }
        
        public string DeleteRecords(StudentService.Student std)
        {
            StudentService.DeleteRecordsRequest inValue = new StudentService.DeleteRecordsRequest();
            inValue.std = std;
            StudentService.DeleteRecordsResponse retVal = ((StudentService.IService)(this)).DeleteRecords(inValue);
            return retVal.DeleteRecordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentService.DeleteRecordsResponse> StudentService.IService.DeleteRecordsAsync(StudentService.DeleteRecordsRequest request)
        {
            return base.Channel.DeleteRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.DeleteRecordsResponse> DeleteRecordsAsync(StudentService.Student std)
        {
            StudentService.DeleteRecordsRequest inValue = new StudentService.DeleteRecordsRequest();
            inValue.std = std;
            return ((StudentService.IService)(this)).DeleteRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentService.SearchStudentsRecordResponse StudentService.IService.SearchStudentsRecord(StudentService.SearchStudentsRecordRequest request)
        {
            return base.Channel.SearchStudentsRecord(request);
        }
        
        public StudentService.ArrayOfXElement SearchStudentsRecord(StudentService.Student std)
        {
            StudentService.SearchStudentsRecordRequest inValue = new StudentService.SearchStudentsRecordRequest();
            inValue.std = std;
            StudentService.SearchStudentsRecordResponse retVal = ((StudentService.IService)(this)).SearchStudentsRecord(inValue);
            return retVal.SearchStudentsRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentService.SearchStudentsRecordResponse> StudentService.IService.SearchStudentsRecordAsync(StudentService.SearchStudentsRecordRequest request)
        {
            return base.Channel.SearchStudentsRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.SearchStudentsRecordResponse> SearchStudentsRecordAsync(StudentService.Student std)
        {
            StudentService.SearchStudentsRecordRequest inValue = new StudentService.SearchStudentsRecordRequest();
            inValue.std = std;
            return ((StudentService.IService)(this)).SearchStudentsRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentService.UpdateStudentsContactResponse StudentService.IService.UpdateStudentsContact(StudentService.UpdateStudentsContactRequest request)
        {
            return base.Channel.UpdateStudentsContact(request);
        }
        
        public string UpdateStudentsContact(StudentService.Student std)
        {
            StudentService.UpdateStudentsContactRequest inValue = new StudentService.UpdateStudentsContactRequest();
            inValue.std = std;
            StudentService.UpdateStudentsContactResponse retVal = ((StudentService.IService)(this)).UpdateStudentsContact(inValue);
            return retVal.UpdateStudentsContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentService.UpdateStudentsContactResponse> StudentService.IService.UpdateStudentsContactAsync(StudentService.UpdateStudentsContactRequest request)
        {
            return base.Channel.UpdateStudentsContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.UpdateStudentsContactResponse> UpdateStudentsContactAsync(StudentService.Student std)
        {
            StudentService.UpdateStudentsContactRequest inValue = new StudentService.UpdateStudentsContactRequest();
            inValue.std = std;
            return ((StudentService.IService)(this)).UpdateStudentsContactAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:14979/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
